### ISSUE TITLE
time since hitting player

### ISSUE THREAD

**Issue by TheMirkMan** [owenstrength/LethalCompanyMod#3]
hey i'm trying to modify your mod in order to give it the config file. i think i'm at a good 98%.
the remaining 2% is softblocked by the variabile "timeSinceHittingPlayer". somehow harmony does not find it, it's the __only__ one giving me problems.
did you have the same problem? if yes how did you fixed it?
i've looked in the source code, the variable exists, it's still there unmodified.

**Comment by owenstrength** [comment]
I think it is a private var. you have publicize the object. Look at source.cs and add it as a reference to plugin.cs

I remember in the code I set it to -5 so that there is a five second buffer between getting hit after being dropped.

**Comment by TheMirkMan** [comment]
it has been done. the mod now has a functional config file, ready to be modified.

**Comment by owenstrength** [comment]
Make a pr if you want and I'll push an update out for the mod

**Comment by TheMirkMan** [comment]
just one thing tho:
the config file's name is still "EvilLootBugByOwen", but it can be fixed only by warning people
